site_name: Customer Lifetime Value Prediction
site_description: lifetime Value for Engaged Customers and New Comers
site_url: https://github.com/caglanakpinar/clv_prediction

repo_name: clv_prediction
repo_url: https://github.com/caglanakpinar/clv_prediction

theme:
  name: material
  features:
    - instant
    - navigation.expand
    - content.tabs.link
    - content.code.copy

nav:
  - getting started: index.md
  - how to run: intro.md
  - configurations: params.md
  - data access: data_access.md
  - pre-process: data_preprocess.md
  - train: train.md
  - hyperparameters: tune.md
  - monitoring: monitoring.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - pymdownx.details
