dash_port: 7003
data_source: null
db_connection:
  data_source:
  db:
  password:
  port:
  server:
  user:
output_file_name: results
port_ranges: 6000*7000
prediction_date: 2020-03-01
server: /tmp/mnt
train_end_date: 2020-01-01
web_port: 7002
